--- 
abstract: Extract meta-data from arbitrary files
author: Florian Ragwitz, C<< <rafl at debian.org> >>
build_requires: 
  ExtUtils::PkgConfig: 0
  IO::File: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: File-Extractor
no_index: 
  directory: 
    - ext
    - inc
    - t
version: 0.03
