---
abstract: 'Extract meta-data from arbitrary files'
author:
  - 'Florian Ragwitz, C<< <rafl at debian.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IO::File: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
  ExtUtils::PkgConfig: 0
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Extractor
no_index:
  directory:
    - examples
    - ext
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
